In [1]:
from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist
import random

In [18]:
np.random.seed(8)
means = [[2, 2], [8, 3], [3, 6]]
cov = [[1, 0], [0, 1]]

N = 4
# X0 = np.random.multivariate_normal(means[0], cov, N)
# X1 = np.random.multivariate_normal(means[1], cov, N)
# X2 = np.random.multivariate_normal(means[2], cov, N)
X0 = [[1, 1], [2, 2], [3, 3], [4, 4]]
X1 = [[100, 100], [101, 101], [102, 102], [103, 103]]
X2 = [[1000, 1000], [1001, 1001], [1002, 1002], [1003, 1003]]
X = np.concatenate((X0, X1, X2), axis = 0)

K = 3 # 3 clusters

original_label = np.asarray([0]*N + [1]*N + [2]*N).T

print(X.shape)
print(original_label.shape)

(12, 2)
(12,)


In [24]:
# khoi tao cac tam cum
def kmeans_init_centroids(X, k):
    # randomly pick k rows of X as initial centroids
    return X[np.random.choice(X.shape[0], k, replace=False)] # replace = False means value can be choose only once

def kmeans_assign_labels(X, centroids):
    # calculate pairwise distances btw data and centroids
    D = cdist(X, centroids) # shape N * k
    # return index of the closest centroid
    return np.argmin(D, axis = 1) # shape N * 1

# t = kmeans_init_centroids(X, K)
# print(t.shape)

# l = kmeans_assign_labels(X, t)
# print(l.shape)

def has_converged(centroids, new_centroids):
    # return True if two sets of centroids are the same
    return (set([tuple(a) for a in centroids]) == set([tuple(a) for a in new_centroids]))

def kmeans_update_centroids(X, labels, K):
    centroids = np.zeros((K, X.shape[1]))
    for k in range(K):
        # collect all points that are assigned to the k-th cluster
        Xk = X[labels == k, :]
        centroids[k, :] = np.mean(Xk, axis=0) # take average
    return centroids

def kmeans(X, K):
    centroids = [kmeans_init_centroids(X, K)]
    labels = []
    it = 0
    while True:
        labels.append(kmeans_assign_labels(X, centroids[-1]))
        new_centroids = kmeans_update_centroids(X, labels[-1], K)
        if has_converged(centroids[-1], new_centroids):
            break
        centroids.append(new_centroids)
        it += 1
    return (centroids, labels, it)

(centroids, labels, it) = kmeans(X, K)
print("Centers found by our algorithms: \n", centroids[-1])


Centers found by our algorithms: 
 [[1001.5 1001.5]
 [   2.5    2.5]
 [ 101.5  101.5]]


In [26]:
from sklearn.cluster import KMeans
model = KMeans(n_clusters=3, random_state=0).fit(X)

print("Centers found by scikit-learn: ")
print(model.cluster_centers_)
pred_label = model.predict(X)
print(pred_label)
# kmeans_display()

Centers found by scikit-learn: 
[[ 101.5  101.5]
 [1001.5 1001.5]
 [   2.5    2.5]]
[2 2 2 2 0 0 0 0 1 1 1 1]
