In [1]:
import numpy as np
from sklearn.neighbors import KNeighborsRegressor

In [28]:
X = np.array([[1, 2, 3], [1, 5, 7], [4, 6, 8], [10, 11, 12],[3, 7, 10]])

y = X.dot(np.array([3, 7, 9])) + 4

neigh = KNeighborsRegressor(n_neighbors=2, weights='uniform')

print(X)
print(y)

neigh.fit(X, y)

[[ 1  2  3]
 [ 1  5  7]
 [ 4  6  8]
 [10 11 12]
 [ 3  7 10]]
[ 48 105 130 219 152]


KNeighborsRegressor(n_neighbors=2)

In [29]:
print(neigh.predict(np.array([[9, 10, 11]])))
print(neigh.kneighbors([[9, 10, 11]], return_distance=False))

[185.5]
[[3 4]]
