In [20]:
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge

# X thuoc N x D, N = 6, D = 3
N = 6
X = np.array([[1, 2, 3], [1, 2, 4], [1, 3, 4], [5, 6, 7], [5, 8, 9], [1, 1, 1]])
t = np.array([[1] for _ in range(N)])
X = np.concatenate((t, X), axis=1)
y = np.dot(X, np.array([1, 2, 3, 4]))
print(X)
print(y)

reg = LinearRegression().fit(X, y)
print(reg.coef_)
print(reg.intercept_)

[[1 1 2 3]
 [1 1 2 4]
 [1 1 3 4]
 [1 5 6 7]
 [1 5 8 9]
 [1 1 1 1]]
[21 25 28 57 71 10]
[0. 2. 3. 4.]
0.9999999999999787


In [32]:
reg.predict([[7, 8, 10, 11]])[0]

91.00000000000006

In [36]:
# Linear Regression Ridge
clf = Ridge(alpha=1.0)
clf.fit(X, y)

print(clf.predict([[7, 8, 10, 11]]))
print(clf.coef_)
print(clf.intercept_)

[90.53333333]
[0.         2.02298851 3.15574713 3.75      ]
1.541954022988513
