In [4]:
# A_mxn = U_mxm * Z_mxn * (V_nxn).T
# U va V la cac ma tran thuc giao
# Z la 1 ma tran duong cheo

from __future__ import print_function
import numpy as np
from numpy import linalg as LA

m, n = 3, 4
A = np.random.randn(m, n)

U, S, V = LA.svd(A) # A = U * S * V (no V transpose here)

# checking if U, V are orthogonal and S is a diagonal matrix with nonnegative decreasing elements
print("Frobenius norm of (UU^T - I) = ", LA.norm(U.dot(U.T) - np.eye(m)))
print("S = ", S)
print("Frobenius norm of (VV^T - I) = ", LA.norm(V.dot(V.T) - np.eye(n)))

print(U)
print(V)

Frobenius norm of (UU^T - I) =  1.6468273425703317e-15
S =  [3.35255041 2.21214132 0.66304079]
Frobenius norm of (VV^T - I) =  6.287224812595087e-16
[[ 0.81382072 -0.54185835  0.20996514]
 [-0.24885094  0.00154966  0.96854056]
 [ 0.52513716  0.8404684   0.13358081]]
[[ 0.4439778  -0.39055841 -0.50003519 -0.63270265]
 [-0.30025973 -0.48493743  0.68523993 -0.4529084 ]
 [ 0.26643178 -0.73146016  0.01386057  0.62752532]
 [-0.80108795 -0.27796737 -0.52935709  0.02780832]]


In [6]:
# print(np.eye(3))
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.dot(a.T))
print(np.linalg.norm(a, ord='fro'))

[[14 32]
 [32 77]]
9.539392014169456
