In [1]:
a = 1
b = 2
print(a + b)

3


In [3]:
import numpy as np

a = np.array([[1, 2, 3, 4]])
b = np.array([[1, 2, 3, 4]])

print(a.T.dot(b))

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
